### PR TITLE
Add information about the character

### PR DESCRIPTION
**Pull request by dev-sankhadip**
According to mentioned issue, when onclicked  character image, i fetched character details(all comics, series, events, stories, his bio url) using marvel api and showed them in a modal using tabs for each category.

#3

### CODE REVIEW

**Comment by sudipt1999** [comment]
Kindly attach some screen shot or gif !

**Comment by dev-sankhadip** [comment]
Screenshot from 2019-12-04 16-53-36
Screenshot from 2019-12-04 16-53-51
Screenshot from 2019-12-04 16-53-56
Screenshot from 2019-12-04 16-53-59
Screenshot from 2019-12-04 16-54-03

**Comment by dev-sankhadip** [comment]
These are screem shots...

**Comment by sudipt1999** [comment]
Great work!

**Pull request merged**
