### PR TITLE
animation updated

### PR DESCRIPTION
**Pull request by dev-sankhadip**
animation updated for issue #2

### CODE REVIEW

**Comment by sudipt1999** [comment]
Add gif here if possible!

**Comment by dev-sankhadip** [comment]
File size is larger than 10 mb, can i send you in your email?

**Comment by sudipt1999** [comment]
Sure !

**Comment by dev-sankhadip** [comment]
I have sent gif

**Comment by sudipt1999** [comment]
Great work!

**Comment by dev-sankhadip** [comment]
Thanks

**Pull request merged**
